#!/bin/bash

APP_PATH=${APP_PATH:-.}
SCRIPT_NAME='script/resque'
PID=$APP_PATH/tmp/resque.pid

sig () {
  test -s "$PID"
}

case "$1" in
  start)
    cd $APP_PATH
    sig || PIDFILE=$PID BACKGROUND=true INTERVAL=2 QUEUE=* ./bin/rake resque:work
        ;;
  stop)
    kill `cat $PID`
    sleep 2
    rm -rf $PID
    ;;
  force-stop)
    kill -9 `cat $PID`
    rm -rf $PID
    ;;
  *)
    echo "Usage: $SCRIPT_NAME {start|stop|restart}" >&2
    exit 3
    ;;
esac

