#!/bin/bash

APP_PATH=${APP_PATH:-.}
SCRIPT_NAME='script/resque'
DAEMON="bundle exec rake resque:work QUEUE=operation"
PID=tmp/resque.pid

case "$1" in
  start)
        cd $APP_PATH && PIDFILE=$PID BACKGROUND=true INTERVAL=2 rake resque:work QUEUE=operation
        ;;
  stop)
        kill `cat $PID`
        sleep 2
        ;;
  force-stop)
        kill -9 `cat $PID`
        ;;
  *)
        echo "Usage: $SCRIPT_NAME {start|stop|restart}" >&2
        exit 3
        ;;
esac

